### ISSUE TITLE
[SUGGESTION] Lower the total game volume?

### ISSUE THREAD

**Issue by stupxd** [DPS2004/Beatblock-issues#10]
**Is your suggestion related to a problem? Please describe.**
I wanted to lower the game volume a little bit just to realize it's already at 1 by default. It seems really odd because my system volume is already at 50% and the game is pretty loud at volume setting 1, which I don't mind usually, but when I'm in VC and can't tone it down, it feels annoying.

**Describe the solution you'd like**
Ability to change the volume more than by 10% or make the general game volume quieter

**Comment by DPS2004** [comment]
The default volume setting should be 7, last I checked? a volume setting of 1 should be very quiet.

**Comment by stupxd** [comment]
Ah, probably the settings carried over from the itch.io version. 

Either way, volume at 1 does not feel very quiet on my pc (also I'm using headphones) with 50% system volume.

**Comment by sk-slimeking** [comment]
> Ah, probably the settings carried over from the itch.io version.
> 
> Either way, volume at 1 does not feel very quiet on my pc (also I'm using headphones) with 50% system volume.

then... decrease the system volume...............

**Comment by stupxd** [comment]
> then... decrease the system volume...............

incredible solution!
