### ISSUE TITLE
[SUGGESTION] No more booting to the top of song list

### ISSUE THREAD

**Issue by Regale-Tress** [DPS2004/Beatblock-issues#100]
**Is your suggestion related to a problem? Please describe.**
adding like 10 songs and then playing one and having to scroll down to the next unplayed song makes me want to kill myself

**Describe the solution you'd like**
dont boot to the top of song list when the song is over, or add a toggle to do not that

**Describe alternatives you've considered**
adding a searchbar like ig. that doesn't fix the issue completely but that would also be nice

**Additional context**
i should go to sleep tbh i've had a fucking whirlwind in the last since like 8 oclock but alas. i need to stop procrastinating my essayu.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
This should have been fixed in the latest version. Are you sure your game is updated?

**Comment by Regale-Tress** [comment]
can i delete this i was like "oh beatblock updated i wonder if it changed it" i read it didn't see it go like "oh i should suggest that" moment i read this yup there it is middle of the screen man im tired :sob:

tho while i'm here ig manual sorting and a search bar would be quite nice!!! i'd love to have all my folders float to the top or just be able to look up an artist name
