### ISSUE TITLE
[BUG] Not responding to mouse movement ingame.

### ISSUE THREAD

**Issue by Woganog** [DPS2004/Beatblock-issues#102]
**Describe the bug**
Some time after enabling the Lock Mouse to Window setting and after I exited a beatmap I made, any time I played the game, the mouse became invisible while on the window in a level. This persisted even after changing the setting again, so I made a new save file. Now, the mouse is visible but still unresponsive in gameplay.

**To Reproduce**
1. ??? I have no idea how this happened unfortunately

**Expected behavior**
I expect the game to respond to mouse movement and rotate the paddle.

**Screenshots**
![Screenshot 2024-08-21 22-28-21](https://github.com/user-attachments/assets/2158f53f-f2bc-434c-b72c-f11bff66371e)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by Woganog** [comment]
When I restarted my laptop entirely, the bug was gone. Also, the invisible mouse was 100% due to having Large cursor on in conjunction with this bug. Still no idea how I caused this

**Comment by OblivionCreator** [comment]
This is likely due to 'force mouse&keyboard' not being enabled and a controller being plugged into your computer.
