### ISSUE TITLE
[SUGGESTION] add left and right click to control settings

### ISSUE THREAD

**Issue by Avelia-tr** [DPS2004/Beatblock-issues#107]
**Is your suggestion related to a problem? Please describe.**
when playing with a tablet (more specifically dragging the pen)the left click is allways activated causing tap not to be hittable
 
**Describe the solution you'd like**
I just want the possibility of deactivating those button without having to go in my tablet driver cuz that is quite annoying to do

**Describe alternatives you've considered**
make the game not block input when one is constantly inputted ? maybe idk

**Additional context**
currently putting both my input on tap(alt) do the trick but I think this can pause problem due to hold time for faster note 

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
An option to disable clicking the mouse to tap has been added in the next update.
