### ISSUE TITLE
[BUG] mouse invisible in retry/quit menu when using Circle snap setting

### ISSUE THREAD

**Issue by Merty8** [DPS2004/Beatblock-issues#108]
when using circle snap and trying to restart the level by pressing esc, the mouse is still invisible and makes it very difficult to choose a specific option.

go to settings > gameplay > circle snap > enable.
next, go into any level, and press escape to bring up the menu.
mouse is still invisible.

the mouse should be invisible up until the point the esc key is pressed and the menu is shown, at that point, the mouse should show.

**Comment by DPS2004** [comment]
Fixed in dev
