### ISSUE TITLE
[SUGGESTION] esc should work to go back when in settings menu

### ISSUE THREAD

**Issue by Merty8** [DPS2004/Beatblock-issues#109]
I always have to specifically press the back button when in the settings menu. i'm not sure if this should be classified as a bug or not, but it's quite annoying.

when in the settings menu, just like any other menu, pressing the esc key should go to the menu the current menu is nested within.

example, say were in:
main menu > settings > gameplay

pressing esc should bring us to
main menu > settings

pressing it a third time should bring us to main menu.

not only would it add consistency between menus but also make traversing them feel nicer.

**Comment by OblivionCreator** [comment]
Fixed for next update. 

Hitting the keybind assigned to back will now go back in the menus.
