### ISSUE TITLE
[BUG] {Linux} Game running prevents KWin effects and screeshotting

### ISSUE THREAD

**Issue by Gotchfutchian** [DPS2004/Beatblock-issues#11]
**Description**
Beatblock uses some rendering method that breaks KDE Kwin effects, along with spectacle screenshotting. (Using XOrg)

**To Reproduce**
1. Open Beatblock
2. Spectacle no longer can screenshot (Steam overlay can, however)
     - Spectacle complains about not having a .service file, the exact error it punches out is
'The name org.kde.KWin.ScreenShot2 was not provided by any .service files
Potentially relevant information:
- Method: CaptureScreen
- Method specific arguments: "DP-0" '

3. All KWin effects (on my machine, moving windows makes them wiggle) dont work

**Expected behavior**
Screenshotting and KWin effects work while the game is open

**Recording**

https://github.com/DPS2004/Beatblock-issues/assets/36716885/2451889a-b0b1-4166-beb4-3334a93fb5db

**Additional context**
This is, of course, a Linux exclusive issue. I can always work around the screenshot issue by using steam overlay to screenshot my stuff, spectacle is nice for rectangular region stuff. System info is below, if its helpful.
![image](https://github.com/DPS2004/Beatblock-issues/assets/36716885/f39665ad-c95b-409e-afa5-49454bc59a4b)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
As discusssed in the discord, likely an issue with love2d itself and/or your specific setup, so not something we can reasonably fix

**Comment by Blue-Beaker** [comment]
Just turn off "Allow applications to block compositing" in KDE system settings -> display and monitor -> compositor section.
