### ISSUE TITLE
[BUG] Paddle 1 set to <25 width speed limit.

### ISSUE THREAD

**Issue by GitHLurker** [DPS2004/Beatblock-issues#112]
**Describe the bug**
If you set the paddle 1 width to anything below 25 you are limited to how fast you can turn (regardless of what paddle is active). This is permanent until you set paddle 1 back to something ≥25. This doesn't happen for any other paddles so I assume its not to help with accuracy on small paddle sections of songs.

**To Reproduce**
1. Change paddle 1 width to something <25
2. Try to spin as fast as possible. (I use a hold at 0° with a block at 180° halfway through the hold and try to hit both with a quick spin.)
3. Set Paddle 1 to something ≥25 to see spin speed difference. (optional)

**Expected behavior**
No spin speed change or only speed change as long as Paddle 1 is enabled. Or have it apply if any paddle is <25 as long as said paddle is enabled.

**Additional context**
I now have a fix for the speed limit through testing but I dont think it should happen in the first place. (It seems unintentional and inconsistent.)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Fixed for next release.

**Comment by OblivionCreator** [comment]
(the speed cap will now be based off of the slowest currently active paddle)
