### ISSUE TITLE
[SUGGESTION] An audio setting to mute the game when unfocused

### ISSUE THREAD

**Issue by Abysalyn** [DPS2004/Beatblock-issues#115]
When I have the game (Beatblock) unfocused, I can still hear the music out of the game, which makes it really irritating when I have to go into the settings and turn the game volume down manually.

**The solution I would like is an audio setting that toggles whether sounds from the game are heard/played when the game is unfocused.** When the setting is toggled on and the game detects that I am unfocused, the game automatically mutes itself. Normally, I would manually mute the menu music, but that can be irritating when I switch from playing the game into doing something else because I have to mute and unmute the game continuously. Furthermore, sometimes I want the menu music when I am focused and in on the game (maybe looking through other levels or such).

I have not thought of other alternatives or additional context of this suggestion, however, I have made a small concept design of how it might look if this suggestion was implemented in the game :

---
![Mute on unfocus suggestion illustration](https://github.com/user-attachments/assets/a7887472-113c-4f3e-a076-13f382d2ced3)

---

That's all!

**Comment by B1rb3** [comment]
An alternative is a simple mute button in a corner that simply mutes the whole thing if coding this will be annoying to (I have no knowledge about coding)

**Comment by OblivionCreator** [comment]
Added for next update

**Comment by B1rb3** [comment]
Hooray

**Comment by Abysalyn** [comment]
> Added for next update

Thanks!
