### ISSUE TITLE
[BUG] Some of the easings don't work on hold notes.

### ISSUE THREAD

**Issue by abugida-iguess** [DPS2004/Beatblock-issues#118]
**Describe the bug**
Some of the in-out easings (namely inOutExpo, inOutCirc, inOutElastic and inOutBack) don't appear to work at all on hold notes.

**To Reproduce**
1. Place a hold note in the editor
2. Set easing to one of the easings mentioned above
Note how the hold note is identical to one without any easing selected.

**Expected behavior**
The easings should have a visible effect on the hold note.

**Screenshots**

![image](https://github.com/user-attachments/assets/69a17a24-ac52-4053-8a4b-a0c6568d5879)

**Additional context**
These easings work as expected on ease events, as well as other events that specify an easing. This only appears to be an issue on hold notes in particular.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Fixed for next release.
