### ISSUE TITLE
[BUG] Credits music does not care about music volume setting

### ISSUE THREAD

**Issue by stupxd** [DPS2004/Beatblock-issues#12]
**Describe the bug**
When you open credits, the music plays at max volume.

**To Reproduce**
1. Go to main menu
2. Click on Credits
3. Experience music play at max volume

**Expected behavior**
Volume setting to be applied

**Additional context**
_Luckily I had my headphones off when I discovered it_

Also I did multiple comparisons with volume setting at 1 and 10 - there's no difference. When I test this on any level, I can hear the difference clearly.

**Comment by DPS2004** [comment]
ah, sorry... will fix that now

**Comment by DPS2004** [comment]
Fixed in dev, thanks for reporting this!
