### ISSUE TITLE
default cursor shows on top of custom cursors

### ISSUE THREAD

**Issue by flodoesstuff** [DPS2004/Beatblock-issues#121]
when using a custom cursor, the default cursor is also visible on top of it

1. Go to 'settings'
2. Go to 'controls'
3. Go to 'mouse controls'
4. Enable either custom cursor
5. Play any chart
6. See bug

the default cursor should not be shown when a custom cursor is enabled, like how it worked in the previous patch

i would attatch a screenshot, however Win+Shift+S automatically removes the default cursor from the screenshot

i have tested this with both custom cursors and in windowed, fullscreen, and fullscreen borderless. no luck

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev

**Comment by flodoesstuff** [comment]
ty!
