### ISSUE TITLE
[SUGGESTION] note hold direction

### ISSUE THREAD

**Issue by getnreal** [DPS2004/Beatblock-issues#122]
**Is your suggestion related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the suggestion here.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Please resubmit with the correct formatting and more details.
