### ISSUE TITLE
[BUG] Disable Barlies Still Defaults to "Disabled" Upon Restart

### ISSUE THREAD

**Issue by Dachi40** [DPS2004/Beatblock-issues#123]
I enabled the option before playing the level, play all the way through and hit retry, suddenly I'm gaining barlies again. This is easy to replicate, just make a short level with a block and enable the option. Play through the level then hit retry at the end and the option will be disabled.

**Comment by OblivionCreator** [comment]
Thanks for the report! Fixed for next release.
