### ISSUE TITLE
legacy accuracy option

### ISSUE THREAD

**Issue by flodoesstuff** [DPS2004/Beatblock-issues#126]
in the previous patch, accuracy was based on the notes you had already passed rather than the notes in the entire chart. what i mean by this is that in a chart with 10 blocks, if you missed the first one and hit the rest, it would show 0% then 50 on the second one then 66 then 75 and so on and so forth until it reaches the last note and hits 90. in the *current* patch, it will just show 90% the entire time. i, and many others, prefer the old system more than the current one.

ideally, there would just be a toggle for legacy accuracy. or it could be called like "fixed accuracy" (current patch) and "dynamic accuracy" (previous patch)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
