### ISSUE TITLE
[SUGGESTION] Allow to change default positions of editor gui.

### ISSUE THREAD

**Issue by astrob4t** [DPS2004/Beatblock-issues#127]
**Is your suggestion related to a problem? Please describe.**
It's rather annoying swapping my event picker and event editor every time I open it since I prefer them to be on the other sides

**Describe the solution you'd like**
Make it so it keeps my layout from last time I opened editor and maybe add a menu to reset it to default

**Describe alternatives you've considered**
A button to set a layout as default and one to reset that

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Added in dev
