### ISSUE TITLE
[BUG] unable to unsnap tools in place

### ISSUE THREAD

**Issue by getnreal** [DPS2004/Beatblock-issues#129]
**Describe the bug**
i accidently put the "snap" tool into the bottom screen and i cant undo it

**To Reproduce**
1. Drag the snap tool to the bottom
2. thats it

 
**Expected behavior**
i expected to be remove the snap tool from the bottom screen and put it wherever i want

**Screenshots**
If applicable, add screenshots to help explain your problem
![help1](https://github.com/user-attachments/assets/04e855c1-7fae-4d55-8847-682c56fbb207)

**Additional context**
spaghetti legs

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
A reset position hotkey has been added in dev
