### ISSUE TITLE
[BUG] flashing lights when changing display mode

### ISSUE THREAD

**Issue by raslei1** [DPS2004/Beatblock-issues#134]
**Describe the bug**
When you change display modes the game will get slower and also flashy

**To Reproduce**
1. Go to Settings, Graphics
2. Set your display mode to fullscreen
3. Tap left twice

**Expected behavior**
Flashing lights and the game running slower

**Screenshots**
https://discord.com/channels/756193219737288836/789126020384686092/1280711167601414249 
video

**Additional context**

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
It's acting almost as-if you are repeatedly tapping left/right arrows.

Are you still encountering this issue? If so, would it be possible to get details information regarding your setup?

Assuming you're running on Windows, please try to open the 'System Information' app and then screenshot the 'System Summary' page and the 'Components -> Display' Page (as below:)

![image](https://github.com/user-attachments/assets/5b08aa9e-543e-4310-824b-8222c745f3fc)
![image](https://github.com/user-attachments/assets/cdefcc97-6437-43cc-97ab-ef496c72f2b0)

**Comment by raslei1** [comment]
it stopped happening quite a while ago, an update probably fixed it but i
don't know which

**Comment by DPS2004** [comment]
Closing as complete
