### ISSUE TITLE
[BUG] costum songs with image previews that dont clear the previous song image

### ISSUE THREAD

**Issue by gamefalor** [DPS2004/Beatblock-issues#135]
**Describe the bug**
what the title says

**To Reproduce**
https://discord.com/channels/756193219737288836/1279550404182413484
install this song, it has this behaviour when scrolled to

**Expected behavior**
it to clear the entire image before displaying the new one

**Screenshots**
![image](https://github.com/user-attachments/assets/25642805-ee85-4ed1-843b-ddb5aa1dedde)

**Comment by DPS2004** [comment]
I'm going to say this is intentional, mostly because I've seen some people do cool stuff with it. If you don't want this effect to happen, it can be fixed by simply expanding the bounds of the image in an editor and removing all transparent pixels.
