### ISSUE TITLE
right clicking to delete on multiple events including holds doesnt work anymore

### ISSUE THREAD

**Issue by flodoesstuff** [DPS2004/Beatblock-issues#136]
**Describe the bug**
when right clicking on a space with multiple events, the menu for choosing which event to delete no longer works if a hold is one of the events and you cant close it in any way other than exiting and reentering the editor

**To Reproduce**
1. place two events on top of each other (one being a hold)
2. right click where the events are
3. attempt to select one to delete in the menu that pops up
4. see error (doesnt work)
5. attempt to close the menu
6. see error (doesnt close)

**Expected behavior**
for it to delete the event you select in the menu, and for the menu to close when you click the x on it

**Screenshots**
![image](https://github.com/user-attachments/assets/6533b3de-8b23-4d6f-be7d-1b5a67c1d4f7)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
I can't reproduce this at all - could you please try again in the latest release (0.3.1)?

**Comment by DPS2004** [comment]
Closing as has been more-info-required for over 2 weeks with no response

**Comment by flodoesstuff** [comment]
sorry abt no response -w- i can try to recreate it now but it also could have been fixed or something

**Comment by flodoesstuff** [comment]
yeah i got it to work, specifically you have to attempt to delete the hold and it breaks. updated steps:

place block
place hold on block
right click on hold and block at the same time
attempt to delete hold
can no longer delete either or close the menu

**Comment by flodoesstuff** [comment]
nevermind! the way to get it to work is that you have to deselect them and then attempt to delete them. then selecting either seems to brick the menu

**Comment by flodoesstuff** [comment]
oh and also its apparently not just with holds

**Comment by flodoesstuff** [comment]
oh and also tabbing out and back into the game while the menu is bricked un-bricks it
