### ISSUE TITLE
[SUGGESTION] Inverse holds and sides

### ISSUE THREAD

**Issue by getnreal** [DPS2004/Beatblock-issues#137]
**Is your suggestion related to a problem? Please describe.**
no

**Describe the solution you'd like**
2 new notes (inverse hold and inverse side)

**Describe alternatives you've considered**
making inverse blocks an option instead of a note it self, but it just will take up too much time to repeatedly place and activate the option

**Additional context**
among us

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by getnreal** [comment]
I FORGOT TO ADD TITLE

RAHHH

**Comment by getnreal** [comment]
ok there

**Comment by DPS2004** [comment]
Not planned at the moment, mostly because of readability concerns.
