### ISSUE TITLE
[BUG] game crash when open

### ISSUE THREAD

**Issue by NightedYT** [DPS2004/Beatblock-issues#138]
the game crash every time i open it

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

[crashlog-1723589591.txt](https://github.com/user-attachments/files/16913679/crashlog-1723589591.txt)

**Comment by DPS2004** [comment]
You are not on the latest version of the game. Additionally, it's not crashing when you open it, but when you are in the song select. I suggest updating your game and deleting your installed custom levels.
