### ISSUE TITLE
[BUG] game crashing after song

### ISSUE THREAD

**Issue by tkiepuszew** [DPS2004/Beatblock-issues#140]
**Describe the bug**
A game crash after completing a custom song

**To Reproduce**
1. [Download Custom map](https://cdn.discordapp.com/attachments/1264639787902435439/1264641263945383980/Girl_Hell_1999.zip?ex=66de8d35&is=66dd3bb5&hm=0fa1540c287d2e52ff573ffc9480175c2f9e2a081f5b7ed09749871031bbfd58&)
2. complete map
3. crash

**Expected behavior**
your normal result screen

**Screenshots**
![image](https://github.com/user-attachments/assets/d8007cd3-f5e7-4352-9b1a-21f324a694b6)

**Additional context**
none

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

Crash logs: 
[crashlog-1725276593.txt](https://github.com/user-attachments/files/16921713/crashlog-1725276593.txt)
[crashlog-1725779650.txt](https://github.com/user-attachments/files/16921714/crashlog-1725779650.txt)

**Comment by DPS2004** [comment]
Seems to be related to having multiple "show results" events.

**Comment by OblivionCreator** [comment]
Fixed for next release, thanks for the report!
