### ISSUE TITLE
[BUG] Game crashed at control settings

### ISSUE THREAD

**Issue by Enoltd** [DPS2004/Beatblock-issues#146]
**Describe the bug**
Game crashed after the trying to remap controls to uncommon key

**To Reproduce**
1. Go to gameplay control menu
2. set a tap control to "é" (i use a french keyboard)
3. Press on "back" button on screen
4. Crash

**Expected behavior**
After pressing on back, the player should be sent back into the control options (menu controls, gameplay controls etc.) and the é key should be working as a tap

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Likely Dguplicate of #113
