### ISSUE TITLE
[SUGGESTION] Song permission template for Beatblock

### ISSUE THREAD

**Issue by sk-slimeking** [DPS2004/Beatblock-issues#147]
**Is your suggestion related to a problem? Please describe.**
As of the current situation right now, asking artists for their permission is tiring, I would not like to write out a whole 30 page essay on why I have to use a specific song for a niche Rhythm game. Not only will this solve many of mine, and other players problems on trying to ask artists for their permission, and to also ease the process.

**Describe the solution you'd like**
Add a song permission template like what [Osu!](https://osu.ppy.sh/community/forums/topics/316083?n=1) did, make it short and brief and a template for asking labels and artists for their personal permission of using songs.

**Describe alternatives you've considered**
The only alternative I could thing of is not doing this suggestion.

**Additional context**
None.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Because we can't officially endorse 99% of custom levels, this is out of the scope for our team as of now. However, this might be a good thing to suggest to the people running the custom level communities, as properly asking for permission is always a good thing in our books!
