### ISSUE TITLE
[BUG] Input offset does not offset visuals

### ISSUE THREAD

**Issue by zoeleu** [DPS2004/Beatblock-issues#152]
**Describe the bug**
When using bluetooth headphones, and calibrating the input offset, the visuals are not offset to the delay, causing weird behavior.

**To Reproduce**
1. Use bluetooth headphones
2. Calibrate to ~200ms or more
3. Play the game
4. Look at the rings

**Expected behavior**
The visuals are offset to make behavior with delayed audio sources work properly, or a separate "audio offset" be created.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
With the way the game works, visual offset kinda can't be done. Visual offset wouldn't affect just the rings, but the blocks too, making things offset from the player in a very weird way. Unfortunately the solution is to not use bluetooth headphones, and to use a lower calibration.

**Comment by zoeleu** [comment]
Maybe instead of offsetting visuals, playing the audio early would work? An audio offset would fix the bluetooth issue entirely.
