### ISSUE TITLE
[BUG] There is no way to unpause a level

### ISSUE THREAD

**Issue by zoeleu** [DPS2004/Beatblock-issues#153]
**Describe the bug**
When paused, there is no button to click, or key to press, to unpause a level, forcing you to quit or restart.

**To Reproduce**
1. Open a level
2. Pause
3. Try to unpause

**Expected behavior**
Pressing escape, or having a resume button to unpause the level

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by aedr1en** [comment]
while i'm not a dev for beatblock, i do know that there's currently no way to unpause a level and that it is currently intentional.

**Comment by DPS2004** [comment]
Added in latest version
