### ISSUE TITLE
[SUGGESTION] Allow to choose which folder to use for custom levels

### ISSUE THREAD

**Issue by Hustuha** [DPS2004/Beatblock-issues#154]
**Is your suggestion related to a problem? Please describe.**
I have multiple storage devices on my pc, and I can't really afford to use the space in the storage device the game defaults to finding custom levels from

**Describe the solution you'd like**
Allowing to choose which directory the game finds custom charts from

**Describe alternatives you've considered**
Instead of using a folder in AppData, use folder inside the game's installed main directory to store custom charts

**Additional context**
![Screenshot_914](https://github.com/user-attachments/assets/25f8fa3e-438c-4428-973a-8927db1cac00)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Unfortunately the level folder has to be in appdata due to an engine limitation. You might be able to get around this with symbolic links, but I can't guarantee it will work.
