### ISSUE TITLE
Block video

### ISSUE THREAD

**Issue by b4llEx** [DPS2004/Beatblock-issues#156]
---
name: Block video
about: It's an idea where the person can put a .mp4 video for the background of the level (within the gameplay of the video.)
title: "Video block"
labels: suggestion
assignees: 'You can set some values, like, being able to put the video on top of the gameplay or not, etc, I think this will make it easier to use decoration, Example: 
Size of video:
X:
Y:
...'

---

**suggestion problem**
I'm always frustrated when I remember that I need to leave the images or decorations in red, blue, yellow, white, cyan etc.

**solution you'd like**
That's why I want you to add the video block.

**alternatives you've considered**
Take away the obligation of the images to have to stay in the colors of red, blue, green, etc.

**Additional context**
Image exempl: https://ibb.co/9YY0Ntd

**Comment by DPS2004** [comment]
Not planned, at least not for now. Videos encourage lazy vfx by just letting people directly import music videos that don't fit into the beatblock style, and also bloat filesize tremendously. If we do add video support, it will likely follow the same restrictions that images have in terms of colors.

**Comment by b4llEx** [comment]
ok, but i have a question, why does the game only accept certain color terms?

**Comment by flodoesstuff** [comment]
because this game was originally made for the handheld "Playdate" console, which only allowed up to 4 colors. this limitation was kept (though extended to 8 colors) as limitations breed creativity.
