### ISSUE TITLE
Game crashes simply when trying to play

### ISSUE THREAD

**Issue by MasterEnis** [DPS2004/Beatblock-issues#157]
My game crashes whenever I click on 'Play Demo Levels' or 'Custom Levels'. You would think it would be because of corrupted files, but since I used steam to check the integrity of the files, this most likely is not the case.

[Here is the crashlog.](https://github.com/user-attachments/files/17236926/crashlog-1727906516.txt) Any help is appreciated.

**Comment by OblivionCreator** [comment]
Judging by the error, it looks like it's failing to load a level. Were you doing anything in particular when you first encountered this?

Please try:
1) emptying your custom levels folder
2) renaming or deleting your main.sav file (located at %appdata%/beatblock)
3) uninstalling & reinstalling the game

**Comment by DPS2004** [comment]
Additionally, you are on version 0.2.2, which is very old.

**Comment by DPS2004** [comment]
Closing as has been more-info-required for over 2 weeks with no response

**Comment by Car314555** [comment]
this also happened me with custom levels so i need help with finding the custom level folder pls

**Comment by DPS2004** [comment]
@Car314555 please make a new issue instead of commenting on one that has been closed for 8 months.
