### ISSUE TITLE
[BUG] Crash on level end with no notes

### ISSUE THREAD

**Issue by TeraByte-Official** [DPS2004/Beatblock-issues#160]
**Describe the bug**
When finishing a level with no notes in it, the game crashes when showing the results screen. Presumably due to a division by zero.

**To Reproduce**
1. Go to Custom levels
2. Create a new level
3. Place a single Show Results event anywhere in the level and save
4. Exit and play the level until it finishes
5. See error

**Expected behavior**
Honestly, I have no idea *what* would happen.

**Screenshots**
What editor should look like to reproduce bug
![image](https://github.com/user-attachments/assets/4260aa3a-190e-4f20-ab16-9d07f75732cd)

**Additional context**
Here's the crash log:
```
	lib/json.lua:109: unexpected number value 'nan'
stack traceback:
	main.lua:590: in function 'handler'
	[love "boot.lua"]:431: in function <[love "boot.lua"]:427>
	[C]: in function 'error'
	lib/json.lua:109: in function 'encode'
	lib/json.lua:93: in function 'encode'
	lib/json.lua:93: in function 'encode'
	lib/json.lua:135: in function 'encode'
	lib/dpf.lua:24: in function 'saveJson'
	states/Results.lua:56: in function 'initFunc'
	main.lua:172: in function 'init'
	states/Game.lua:104: in function 'goToResults'
	levelformat/events/Gameplay/showResults.lua:14: in function 'endFunction'
	obj/Player.lua:84: in function '_oncomplete'
	lib/flux/flux.lua:173: in function 'update'
	main.lua:199: in function 'update'
	main.lua:477: in function 'update'
	[love "callbacks.lua"]:174: in function <[love "callbacks.lua"]:156>
	[C]: in function 'xpcall'
	[love "boot.lua"]:456: in function <[love "boot.lua"]:423>
```

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
