### ISSUE TITLE
Difficulty number does not display properly in the level select page for custom levels

### ISSUE THREAD

**Issue by Random22wastaken** [DPS2004/Beatblock-issues#161]
**Describe the bug**
In the new editor as of update 0.3.0, if you set the variant difficulty to any number (in this example 5), it still displays the difficulty number as 0 in the menu. It displays properly in the actual level though.

**To Reproduce**
1. Go to the custom levels page.
2. Create a new level + variant.
3. Set the difficulty to any value above 0.
4. Save and go back to the menu.

**Expected behavior**
The difficulty number should have changed if the difficulty is above 0. Instead it remains 0 even when setting a different value.

**Screenshots**
![image](https://github.com/user-attachments/assets/f2e280c5-5a32-488c-81aa-95638420e515)
![image](https://github.com/user-attachments/assets/eb4780e8-ac5f-4895-8f02-510e319cc415)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by Random22wastaken** [comment]
Edit: I may have found the problem. In the manifest, it appears to only change the variant difficulty and not the difficulty for the level as a whole. This extends to the name of the charter as well.
![image](https://github.com/user-attachments/assets/47d9ad19-e53d-4db4-b04e-ddba860bb06a)
![image](https://github.com/user-attachments/assets/2a69f538-6c30-4568-9095-62dd7f8c2b78)

**Comment by OblivionCreator** [comment]
I can't reproduce this locally. Could you send across the level file?
