### ISSUE TITLE
[BUG] Game crashes when using the Play Sound event

### ISSUE THREAD

**Issue by Cytruss-fruit** [DPS2004/Beatblock-issues#162]
**Describe the bug**
When using the Play Sound trigger "improperly", the game instead of warning you, crashes.

**To Reproduce**
1. Go into the level editor for any song
1. Place a Play Sound event
2. Into "sound" insert any string of characters (i.e. SoundEffect, or SoundEffect.ogg or SoundEffect.mp3), any name that isn't present within the level file
3. Play the level
4. Game crashes

**Expected behavior**
I would expect the game to warn me if said file I inputted doesn't exist. Furthermore I expect the trigger to work similar to the "Play song" event, meaning that it accepts the full filename, instead of the name without the file extension.

**Screenshots**
Not necessary in my opinion

**Additional context**
Crash log from one of my attempts
```
--- CRASH LOG ---

	levelformat/events/Vfx/playSound.lua:18: Could not open file Custom Levels/favourites/lawrence/Vine Boom.ogg.ogg. Does not exist.
stack traceback:
	main.lua:590: in function 'handler'
	[love "boot.lua"]:431: in function <[love "boot.lua"]:427>
	[C]: in function 'newSoundData'
	levelformat/events/Vfx/playSound.lua:18: in function <levelformat/events/Vfx/playSound.lua:14>
	obj/GameManager.lua:554: in function 'runQueuedEvents'
	obj/GameManager.lua:469: in function 'resetLevel'
	states/Editor.lua:427: in function 'playLevel'
	states/Editor.lua:221: in function 'func'
	states/Editor.lua:474: in function 'checkKeybinds'
	states/Editor.lua:524: in function 'updateFunc'
	main.lua:190: in function 'update'
	main.lua:477: in function 'update'
	[love "callbacks.lua"]:174: in function <[love "callbacks.lua"]:156>
	[C]: in function 'xpcall'
	[love "boot.lua"]:456: in function <[love "boot.lua"]:423>

```

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev. playSound will now require an extension, and won't crash if it can't find the file. (For published levels that already use playSound without the extension, it will automatically add the extension for you, so nothing needs to be updated)
