### ISSUE TITLE
[BUG] Changing a multitude of colours at once causes the game to crash

### ISSUE THREAD

**Issue by TriTheKitten** [DPS2004/Beatblock-issues#163]
**Describe the bug**
I tried to change 6 colours all at once, and the game just crashed.

**To Reproduce**
1. Go to the editor
2. Place down 6 set colour events on the same beat
3. press P to playtest level

**Expected behavior**

**Screenshots**
https://github.com/user-attachments/assets/f259835d-ec3d-40f3-bded-adbf974219e5

**Additional context**
I was trying to chart caution.ogg and i wanted to have the colours cycle through

and uhhh here's the crashlog
[crashlog-1729058921.txt](https://github.com/user-attachments/files/17390196/crashlog-1729058921.txt)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Can you send the level that causes this crash?

**Comment by DPS2004** [comment]
Closing as has been `more-info-required` for over 2 weeks with no response
