### ISSUE TITLE
[BUG] Play Sound event has no tooltip

### ISSUE THREAD

**Issue by TeraByte-Official** [DPS2004/Beatblock-issues#164]
**Describe the bug**
When hovering over Play Sound in the event palette, it says "No tooltip".

**To Reproduce**
1. Go to Custom Levels
2. Create or edit a level
3. Hover over Play Sound in event palette

**Expected behavior**
The tooltip should be "Plays a sound effect"

**Screenshots**
![image](https://github.com/user-attachments/assets/16caf1f0-9b3a-42e4-9811-670bbd8f8cd6)

**Additional context**
None

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
