### ISSUE TITLE
[BUG] Game crashes when opening menu during song ending

### ISSUE THREAD

**Issue by RealTobyG** [DPS2004/Beatblock-issues#165]
**Describe the bug**
Game crashes when opening the menu (aka esc screen) during the ending part of the song. This is the sort of limbo where the song itself is not finished but the level is. This is a very tight window and needs some good timing to reproduce. It doesn't even show me a crash log it fully closes the app.

**To Reproduce**
1. Play any song
2. Finish said song
3. When the level is finished but the song is not, click esc and attempt to resume
4. Game will crash
5. See error

**Expected behavior**
I expected the game to skip the ending of the song and skip straight to the score and ranking page like what osu! does. And if it doesn't, at least let me resume the game to see the ending.

**Screenshots**
I made a video of me playing the level, the bug can be seen with my key inputs (I forgot to add the esc button my bad, but the screen should show you when I clicked esc, dunno why tab is being held)
https://youtu.be/1q2BzTcM74M

**Additional context**
This might be a Beatblock DEMO bug since I am using the Demo version of Beatblock, but the bug is very interesting.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
