### ISSUE TITLE
[SUGGESTION]  a few ideas

### ISSUE THREAD

**Issue by SirGamers** [DPS2004/Beatblock-issues#17]
**Is your suggestion related to a problem?**
No

**Describe the solution you'd like**
I have a few ideas:

1: pause menu - a pause menu would help a lot but there’d need some way to stop pause buffering. It should have Resume, Restart, Options, and Exit buttons

2: epilepsy warning/toggle - I mean not everyone can have cool effects because of medical reasons (I know a low vfx mode is coming but would it be sufficient enough?)

3: Steam Workshop - not everyone has/wants to make a discord account, so we should have Steam Workshop and there could be tags for WIP stuff and a tag for each mechanic

4: custom file type - do something like osu (.osu) or Rhythm Doctor (.rdzip) where custom levels are stored in a renamed zip file like .bb or something and then have the game associate with that file type and then make it so if people open it, it will import (see below) into beatblock

5: import menu - a menu that you can browse and select a zip (and/or the above idea) and automatically extract it to the custom levels folder

**Describe alternatives you've considered**
Now using Steam Workshop might not work for a couple reasons but one big one: Copyright
So instead I was thinking you guys could make a custom website that works basically the same as Steam Workshop but doesn’t automatically download it (in the same vein as [rhythm cafe](https://rhythm.cafe) (a fan made repository for Rhythm Doctor custom levels))

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
1. A pause menu is under consideration, the real issue is on the programming end of things.
2. We will be adding a togglable epilepsy warning for custom levels, similar to RD.
3. Steam workshop is unlikely to happen due to the copyright issues you mentioned, and if it does it will only be after the full game launches.
4 + 5: This would be a lot of burden on the programming team, and we are prioritizing other features. 
Regarding steam workshop and rhythm cafe, rhythm cafe only really works because its fan run. If *we* made the website, we'd be even more liable for copyright violations than we would be with workshop support.

**Comment by SirGamers** [comment]
> 1. A pause menu is under consideration, the real issue is on the programming end of things.
> 2. We will be adding a togglable epilepsy warning for custom levels, similar to RD.

cool 👍🏼

> 3. Steam workshop is unlikely to happen due to the copyright issues you mentioned, and if it does it will only be after the full game launches.

makes sense

>    4 + 5: This would be a lot of burden on the programming team, and we are prioritizing other features.

yeah, don't push yourselves too hard ok

>    Regarding steam workshop and rhythm cafe, rhythm cafe only really works because its fan run. If _we_ made the website, we'd be even more liable for copyright violations than we would be with workshop support.

yeah, I didn't think about that
