### ISSUE TITLE
[SUGGESTION] Linear tempo changes

### ISSUE THREAD

**Issue by TeraByte-Official** [DPS2004/Beatblock-issues#171]
**Is your suggestion related to a problem? Please describe.**
Songs with linear tempo changes are very hard to chart without LITERALLY DOING CALCULUS

**Describe the solution you'd like**
Give the Tempo Chane event a duration modifier. This will allow the tempo change to be linear.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Duplicate of #29
