### ISSUE TITLE
[BUG] Custom Controller Bindings Don't Save

### ISSUE THREAD

**Issue by jckirton** [DPS2004/Beatblock-issues#181]
**Describe the bug**
I play with controller and bind `Tap` to be `Right Bumper`, but this binding doesn't save and is reset on game launch.

**To Reproduce**
1. Open game
2. Change/Add controller binding
3. Exit game
4. Open game again
5. Changed binding should be missing/lost

**Expected behavior**
I expect the changed binding to be saved and still be there on game launch.

**Screenshots**
N/A

**Additional context**
I am playing on Mac with Whisky + GPTK, but I don't think that's causing the issue.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Are you hitting 'Back' after applying the binding? It only saves the update once you leave the controller binds menu.

**Comment by jckirton** [comment]
> Are you hitting 'Back' after applying the binding? It only saves the update once you leave the controller binds menu.

Yes, I am. I am also closing the game from the in-game menu.

**Comment by OblivionCreator** [comment]
Sounds like it's having trouble saving. Do other options (such as accessibility) save okay?

**Comment by DPS2004** [comment]
Closing as has been more-info-required for over 2 weeks with no response
