### ISSUE TITLE
Music not stopping when needed to

### ISSUE THREAD

**Issue by LuckyOfTheAnimations** [DPS2004/Beatblock-issues#182]
Bassically, my level has... music.
news breaking I know.

my level is somehow diffrent in some sort of way to neglet whatever code you wrote to stop music, in any way.
when I stop previewing, playing, or doing anything with the level the music does not stop.

So I'll have to rejoin the game again and again, instead of pressing P again and again.

I don't know how this even happens though, Because from what I know you completely stop all sounds in the game from happening.

So, I have no idea what to say exactly on why this is happening.
All I did was put a sound thingy, Put the data, data works, data doesn't stop.

**Comment by OblivionCreator** [comment]
Please can you provide the level file? 

Additionally, for future reference, please use the template to report bugs

**Comment by LuckyOfTheAnimations** [comment]
> Please can you provide the level file?
> 
> Additionally, for future reference, please use the template to report bugs

sure. give me a second

**Comment by LuckyOfTheAnimations** [comment]
[Flowers music.zip](https://github.com/user-attachments/files/17921054/Flowers.music.zip)
here

**Comment by OblivionCreator** [comment]
The play sound event is not designed to play level music as it does not properly set BPM/other required settings. 

Use the play song event instead

**Comment by LuckyOfTheAnimations** [comment]
> The play sound event is not designed to play level music as it does not properly set BPM/other required settings.
> 
> Use the play song event instead and that should fix it
> 
> (I'll look into why play sound doesn't stop the sound properly!)

wait so, you don't turn off sounds when leaving?
that could be an awful problem if people do really loud things

**Comment by DPS2004** [comment]
Addressed in dev by adding a warning to the play sound event that it is not meant to be used for music.
