### ISSUE TITLE
[BUG] line that will go forever

### ISSUE THREAD

**Issue by prankstongamer** [DPS2004/Beatblock-issues#19]
**a line that will go on forever**
a line that will go on forever in any direction.

**To Reproduce**
1. Go to 'the editor'
2. place 'ither hold'
3. change the '2nd part of hold to any negative number'

**Expected behavior**
the line will 90% of the time look like a blob that will hurt your eyes.

**Screenshots**
I don't know how.

**Additional context**
its a line.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
