### ISSUE TITLE
[SUGGESTION] Being able to control with the arrow keys instead of mouse

### ISSUE THREAD

**Issue by MAZ12211** [DPS2004/Beatblock-issues#194]
**Is your suggestion related to a problem? Please describe.**
Coming from somebody who played Super Hexagon a lot, it feels really really weird to play & control this game with a mouse instead of 
the left and right keys. It's really frustrating to play.

**Describe the solution you'd like**
An option to play with left and right arrow keys

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Not really something we are planning on, sorry. The game is designed around having fluid control over your angle with varying speeds. There are some patterns of notes that would be impossible to hit with an arrow key control scheme. If playing with a mouse is uncomfortable, maybe try using a controller?
