### ISSUE TITLE
[SUGGESTION] Lock mouse cursor on active monitor

### ISSUE THREAD

**Issue by outget** [DPS2004/Beatblock-issues#20]
**Is your suggestion related to a problem? Please describe.**
When using multiple monitors, the cursor can slide into the other monitors which is kinda disorienting and causes you to lose track of where the cursor is.

**Describe the solution you'd like**
Could be an option under Gameplay which limits the cursor from moving outside the active monitor the game is running in.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Mouse lock was as an option in dev, will be in next update
