### ISSUE TITLE
[BUG] game not opening

### ISSUE THREAD

**Issue by inuchan12** [DPS2004/Beatblock-issues#23]
when I try to open the game, it crashes and gives me this text:
https://github.com/user-attachments/files/16388289/crashlog-1721978828.txt
my PC meets every requirements to play this game

**Comment by inuchan12** [comment]
my pc meets every requirements to play but I cant open it

**Comment by DPS2004** [comment]
Beatblock requires OpenGL 3 at the minimum to launch. This error means your computer does not support it. Try updating your drivers, or playing on a newer device.

**Comment by inuchan12** [comment]
i do have opengl 3.1...
