### ISSUE TITLE
[BUG] game crashing

### ISSUE THREAD

**Issue by inuchan12** [DPS2004/Beatblock-issues#24]
when I try to open the game, it crashes and gives me this text:
https://github.com/user-attachments/files/16388289/crashlog-1721978828.txt
my PC meets every requirements to play this game and i have opengl 3.1

**Comment by DPS2004** [comment]
The next build of the game will use a slightly different version of the game engine, when it comes out maybe try then?

**Comment by DPS2004** [comment]
@inuchan12 has the latest version of the game resolved this issue?

**Comment by inuchan12** [comment]
> @inuchan12 has the latest version of the game resolved this issue?
yes
