### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Megalodon-Shark** [DPS2004/Beatblock-issues#25]
The game crashes when the offset is set to negative, not sure if this is intentional or such, but the window of the game bugs out wheen clicking on other windows and cannot be closed. The audio also keeps playing and the only way to close the game seems to be via task manager.

Go to the level editor and open it
Place a play song event, insert the audio file name and set any negative offset, and press enter.
See error

**Expected behavior**
The negative offset not crashing the game and just, letting negative offset happen

**Additional context**
The song didn't start playing from the beginning of the audio file, but a few (5-10) seconds later when i inserted the .ogg audio file, so i tried setting a negative offset. This was before typing in the negative offset and pressing enter, the song file was named ''777.ogg'' if that helps.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by ishanpm** [comment]
I also ran into this. Crash log: [crashlog-1722385827.txt](https://github.com/user-attachments/files/16434762/crashlog-1722385827.txt)

**Comment by DPS2004** [comment]
Negative offset can no longer be set as of latest build
