### ISSUE TITLE
[SUGGESTION] Editor Fix

### ISSUE THREAD

**Issue by Not-Nik0** [DPS2004/Beatblock-issues#26]
Please make it so you can listen to the song whilst making a chart like in osu. I think the editor itself is fine, it's just missing this one important feature. How the hell do people even make a chart without being able to listen to the song anyways? Please teach me. Sorry if this is already in the editor and I'm just slow and can't find it.

**Comment by OblivionCreator** [comment]
You can already do this by tapping 'P' in-editor.
