### ISSUE TITLE
[SUGGESTION] Directional Indicators for Side Notes

### ISSUE THREAD

**Issue by ThatZeoGal** [DPS2004/Beatblock-issues#3]
**Is your suggestion related to a problem? Please describe.**

Currently, side notes can be confusing. It's hard to tell what direction is recommended to hit from for the "flow" of the chart, and its also quite unclear when a side should be a "flick" (quickly change direction after hitting) or a "follow-through" (keep your momentum smoothly through the note). I think a directional indicator could help a lot with this!

**Describe the solution you'd like**
![side-export](https://github.com/DPS2004/Beatblock-issues/assets/67521686/7a11e161-5f01-4b1a-b281-371418fbf0c0)

You could still hit side notes from either side with your paddle, but directional indicators would be a useful visual change to indicate the greater flow of the level. You could also just use the directionless one if you really wanted.

Why do I think this is a good idea? Well, it's my belief that in a game like this, the difficulty shouldn't come from understanding what to do, but actually executing it. Especially in a rhythm game where you can't just rewind and try again instantly, it's important that the player knows what to do next, even if it's up to them to actually do it. Of course, something like a "guiding line" through the whole chart would remove the sight-reading aspect entirely, so I think these directional notes would be a good fit!

**Describe alternatives you've considered**
While I believe this would be beneficial for all users on all charts, it would still be welcome as an “accessibility/difficulty feature.” However, keep in mind charts would still have to be created with the directional indicators defined.

**Additional context**
The pictured directional notes have more intense curves and arrows for the "hit" side, and flat edges for the other sides.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Not planned at the moment. Well designed charts should ideally lead/cue in the player in what direction to hit the side from, as part of the challenge.
