### ISSUE TITLE
[BUG] Editor crash when changing hold segments to 0

### ISSUE THREAD

**Issue by ishanpm** [DPS2004/Beatblock-issues#30]
**Describe the bug**
The editor crashes when a hold note's `segments` property is set to 0.

**To Reproduce**
1. Go to the editor.
2. Create a hold note.
3. Toggle the `segments` property.
4. Press the `-` button on the segments property.
5. The game crashes.

**Expected behavior**
The value should be clamped to a minimum of 1, or the editor should accept the value of 0 without crashing.

**Screenshots**
N/A

**Additional context**
Game version: 0.2.0 (Demo)
Crash log:  [crashlog-1722387503.txt](https://github.com/user-attachments/files/16434903/crashlog-1722387503.txt)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev, thanks for reporting
