### ISSUE TITLE
Game translation

### ISSUE THREAD

**Issue by V1rnax** [DPS2004/Beatblock-issues#31]
**Describe the solution you'd like**
New channel on discord for translators/translations

**Additional context**
![image](https://github.com/user-attachments/assets/59503168-32da-444e-9a30-c4c55dd16aab)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Currently no plans to make a channel in Discord for this. We do plan on hiring people to localize the game into more languages, though!
