### ISSUE TITLE
[SUGGESTION] Improve menu input handling

### ISSUE THREAD

**Issue by BerryOnGit** [DPS2004/Beatblock-issues#32]
**Is your suggestion related to a problem? Please describe.**
Using the menus is mildly inconvenient because things arent consistent, you can press back to go back to the menu from the level select, but not from the settings? Sometimes the selection randomly drops down 1 item when selecting stuff as well.

**Describe the solution you'd like**
Redo the input handling and also change the back button on controller to B instead of START, work with expectancies

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed as of latest build
