### ISSUE TITLE
[SUGGESTION] Decoration "follow" option

### ISSUE THREAD

**Issue by BerryOnGit** [DPS2004/Beatblock-issues#38]
**Is your suggestion related to a problem? Please describe.**
Thats not an option.

**Describe the solution you'd like**
Since the game already inherits an OOP system itd be quite easy to have an object have access to the values of another, specifically position and rotation.

When the "follow" parameter is ticked on on a Decoration youd be able to either paste the id of the event youd like it to inherit or a keyword for crankys paddle, then you can choose whether or not to inherit the rotation and or position which will make the Decoration set its position / rotation to the targets, with an optional offset being provided as well.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Added as of latest build
