### ISSUE TITLE
[SUGGESTION] Custom Cranky face folder

### ISSUE THREAD

**Issue by BerryOnGit** [DPS2004/Beatblock-issues#39]
**Is your suggestion related to a problem? Please describe.**
Manually placing a face over cranky doesnt have the same effect as setting it and seeing it move around

**Describe the solution you'd like**
A new folder in the levels called "faces" where one could drop in custom face textures, then when setting the face in the respective event itd also consider the face sprites in the custom folder, which also means you cant have faces with the same name as the official ones.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Added in dev
![image](https://github.com/user-attachments/assets/1a7b17c4-b487-487c-ba54-51067e4d5e6a)
![image](https://github.com/user-attachments/assets/5c4ecd9a-4ce9-478e-a2a7-4519c56e9986)
