### ISSUE TITLE
[SUGGESTION] Make the “K” in the logo not have slanted ends

### ISSUE THREAD

**Issue by ThatZeoGal** [DPS2004/Beatblock-issues#4]
**Is your suggestion related to a problem? Please describe.**
Most typefaces avoid slanted ends to block-style letters, as it can cause the percieved length of lines to be inconsistient.

**Describe the solution you'd like**
![logo](https://github.com/DPS2004/Beatblock-issues/assets/67521686/76b3adc8-d887-477a-8b6a-6e268d3f0a20)
Modify the logo to something like this, where the ends of the “K” are in cardinal directions.

**Describe alternatives you've considered**
Eh, you either change it or you don’t lol. Not many alternatives for this.

**Additional context**
![logo-export](https://github.com/DPS2004/Beatblock-issues/assets/67521686/104292ec-b0ad-47b1-940b-fee6f2c028ba)
![logorevised-export](https://github.com/DPS2004/Beatblock-issues/assets/67521686/80aba074-726c-4458-b891-7f9b6c7aeae1)
To better illustrate the point, this is the design principle why slanted ends are generally not preferred.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Resolved in dev
