### ISSUE TITLE
[SUGGESTION] Make BGM built in

### ISSUE THREAD

**Issue by BerryOnGit** [DPS2004/Beatblock-issues#41]
**Is your suggestion related to a problem? Please describe.**
Since this is a rhythm game its probably better to have the game assume there will be a song and just have it be a built in event in the level instead of one you have to place yourself.

**Describe the solution you'd like**
Remove the event, and make a new tab for it where the settings can be changed.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Not planned, Play Song being its own event allows for more versatility. In the future I'd like to allow for multiple play sound events, or something similar.
