### ISSUE TITLE
[BUG] sound costantly stutters/cuts out

### ISSUE THREAD

**Issue by null-VOID-null** [DPS2004/Beatblock-issues#52]
so im using arch linux, and whenever i installed beat block (via the itch.io desktop app) , theres a constant stutter in all sound in game every half second or so. ive tried deleting and reinstalling it multple times, once by the app and the rest via the zip file in the website version, and none of it fixed it.

**Comment by DPS2004** [comment]
What are your system specs and sound device information, and do you have these issues when using the Steam version?

**Comment by OblivionCreator** [comment]
Closed as no response.
