### ISSUE TITLE
[BUG] Game not taking the entire screen when `Display Mode` is set to `Fullscreen`

### ISSUE THREAD

**Issue by ALEZ-DEV** [DPS2004/Beatblock-issues#53]
**Describe the bug**
I have a 21:9 widescreen monitor and when I put the game in fullscreen, the game stay at 16:9 aspect ratio, this is not a big deal now, but will become annoying in the future

**To Reproduce**
1. Go to 'settings/graphics'
2. Change 'Display Mode' to 'Fullscreen'

**Expected behavior**
That the game take the entire screen when the setting 'Display Mode' is on 'Fullscreen'

**Screenshots**
![image](https://github.com/user-attachments/assets/b2a5e351-9f89-4d3c-8f0a-cbe29a212cd5)

**Additional context**
I'm currently on linux with NixOS and I downloaded the demo from steam with the WM Hyprland, but I don't think my config is the issue

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
The game is designed to run at a set resolution. Dynamic resolution would break a lot of things, including notes spawning in thin air, and visual effects that rely on screen positioning.
