### ISSUE TITLE
[BUG] Game Crash on level with too high song negative offset.

### ISSUE THREAD

**Issue by MeGaGiGaGon** [DPS2004/Beatblock-issues#60]
**Describe the bug**
The game crashes when trying to play a level with too high of negative offset.

**To Reproduce**
1. Create new custom level
2. Place a "Play Song" event
3. Select any song and bpm
4. Set song offset to -10
5. Save and play
6. Game crash

**Expected behavior**
Game doesn't crash

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Fixed in version 0.2.1
