### ISSUE TITLE
[SUGGESTION] leniancy value on holds

### ISSUE THREAD

**Issue by tuopi27** [DPS2004/Beatblock-issues#65]
anyone whos fucked around in the editor has noticed that regular hold blocks have a level of "leniancy" where you can move your paddle off for a moment and still keep holding. this can break some layouts but also allows for some fun shenanigans

SO, suggestion: add a "leniancy" value to hold blocks that functuons like tickrate on hold mines and modifies how often it checks whether youre still holding

this way, you can reduce leniancy to stop people from cheesing certain segments, or even increase it for more interesting shenanigans.

**Comment by DPS2004** [comment]
Added via an easable
