### ISSUE TITLE
[SUGGESTION] Customizable mouse sprites.

### ISSUE THREAD

**Issue by K1ngC001** [DPS2004/Beatblock-issues#75]
**Is your suggestion related to a problem? Please describe.**
My suggestion is not related to any problem, just an idea I had while playing.

**Describe the solution you'd like**
Similar to the force player sprite action, something like that could be used to change the mouse sprite for custom levels. The level of course would have to provide the sprite alongside other level resources.

**Describe alternatives you've considered**
Something that could be done is the application could hide the cursor, then have an image provided follow the mouse until the level ends or the sprite is changed again.

**Additional context**
Example:
![untitled](https://github.com/user-attachments/assets/0bef1438-1d85-4713-8587-a9abc2894501)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Not planned, because of both accessibility issues as well as not all users playing with mouse. Admittedly would be pretty fun, though...
