### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NightedYT** [DPS2004/Beatblock-issues#76]
i tried to go to custom level but each time i try the game crashes

here is the crash log:
[crashlog-1723001538.txt](https://github.com/user-attachments/files/16606079/crashlog-1723001538.txt)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Can you try deleting your custom levels? it seems one of them is corrupted
