### ISSUE TITLE
[BUG] Setting the amount of segments to "0" on a "Hold" event will immediately crash the game

### ISSUE THREAD

**Issue by W-Wolfie** [DPS2004/Beatblock-issues#77]
**Describe the bug**
If you set the number of segments on a "hold" note to zero, it will immediately crash the game.

**To Reproduce**
1. Go into the custom level editor.
2. Create a "hold" note.
3. Press on the "segments button".
4. Set the amount of segments to zero.

**Expected behavior**
I expected it to not allow the number to go below one.

**Screenshots**
Here's a video demonstration, along with a crashlog:
https://github.com/user-attachments/assets/4a554691-fff9-4730-aa26-1c4db40ec6c6
[crashlog-1723619457.txt](https://github.com/user-attachments/files/16609011/crashlog-1723619457.txt)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
