### ISSUE TITLE
[SUGGESTION] auto save and save before crash.


### ISSUE THREAD

**Issue by bananharcos** [DPS2004/Beatblock-issues#78]
you know how all games have auto save, and most of them are customizable and has a floppy disk icon 💾 show up, well, you could do that, if its possible.
and if you could, you should make a save before crashes, or the app doesnt close fully, and the level is half remembered, so if the error/crash message appears, it could have a button that at least saves most of the data.
if any of these become true thank you for the convince, and if not, at least thank you for reading this big block of text with the lazyness of sans's dialogue.
love ya'll!

**Comment by DPS2004** [comment]
Autosave will be in the next update. We won't be adding save before crash, though, out of fear of corrupting levels.
