### ISSUE TITLE
[SUGGESTION] Better cursor visibility

### ISSUE THREAD

**Issue by stupxd** [DPS2004/Beatblock-issues#8]
**Is your suggestion related to a problem? Please describe.**
Very often I'd feel so lost when playing a level, and a part of it is the amount of things happening on the screen, but a part of it is also losing sight of the cursor.

**Describe the solution you'd like**
Maybe an option with some fixed colors, or maybe have cursor color change dynamically within the level. Both could work.

**Comment by SirGamers** [comment]
they'd have to make a custom cursor but I agree

**Comment by DPS2004** [comment]
Implemented in latest version
