### ISSUE TITLE
[BUG] Crash after making an object with an invalid name?

### ISSUE THREAD

**Issue by Krono159** [DPS2004/Beatblock-issues#80]
**Describe the bug**
Made an event with name "shake" on the editor

**To Reproduce**
1. Go to custom songs/create new/event palette
2. Click on the bar with the name of events
3. type ''SHAKE''
4. Press enter 
5. place the new object

**Expected behavior**
the game should validate if the event is valid or not, if not, not allow the user to place it and show an error

**Screenshots**
![imagen](https://github.com/user-attachments/assets/a829637c-75dd-460f-8e35-9adec30f4782)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock. (downloaded from Steam)**
[crashlog-1723731335.txt](https://github.com/user-attachments/files/16626304/crashlog-1723731335.txt)

**Comment by DPS2004** [comment]
Fixed in dev
