### ISSUE TITLE
[BUG] Game crash on show results event

### ISSUE THREAD

**Issue by CherryRage** [DPS2004/Beatblock-issues#82]
**Describe the bug**
Game crush after playing Shop - Toby Fox (posted on discord 15.08 by KindaBoring), it crush when result should show. Like it is bug with show results event. 

**To Reproduce**
1. Download Shop-Toby Fox.zip (one attached)
2. Put in custom levels
3. Play it
4. Game crush at the end

**Expected behavior**
Game should not crush after playing chart.

**Screenshots**
(Video and screenshot are from different tries)
https://github.com/user-attachments/assets/2fe0f4f5-51d1-43b4-8377-80825fd46e34

![image](https://github.com/user-attachments/assets/5d73e47e-8703-4f98-b71d-0f11a07bb3ea)

**Additional context**
[crashlog-1723757596.txt](https://github.com/user-attachments/files/16630688/crashlog-1723757596.txt)

[Shop - Toby Fox.zip](https://github.com/user-attachments/files/16630690/Shop.-.Toby.Fox.zip)

**By submitting this, I am confirming that 

I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev, the level creator forgot to add a level select image. This wont crash in the next version, though.
