### ISSUE TITLE
[SUGGESTION] Add setting that makes the controls based on mouse movement rather than mouse position

### ISSUE THREAD

**Issue by jensen-melody** [DPS2004/Beatblock-issues#84]
**Is your suggestion related to a problem? Please describe.**
Whenever I'm playing any difficult song, my mouse ends up drifting to one side so when I try and move my mouse back to the other side it doesn't actually get to where I need it to get to

**Describe the solution you'd like**
A setting (probably in accessibility) that locks the mouse into the middle of the screen and sets the direction of the paddle to the direction the mouse moved in last (kind of like if the mouse was a joystick or something)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Have you tried out circle snap mode?

**Comment by OblivionCreator** [comment]
Already implemented in circle snap mode.
