### ISSUE TITLE
install custom tracks ingame

### ISSUE THREAD

**Issue by Phoenixbeast123** [DPS2004/Beatblock-issues#87]
**Is your suggestion related to a problem? Please describe.**
add a menu in game to install custom tracks with a audio preview

**Describe the solution you'd like**
a simple menu with search capabilities. like the discord. but just put ingame.

**Describe alternatives you've considered**
a seperate webpage ig?

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
this is wildly out of scope for us. we don't have the budget or resources to have an in-game level browser, very few games do.
