### ISSUE TITLE
[SUGGESTION] Static rotation for paddles

### ISSUE THREAD

**Issue by Whatares** [DPS2004/Beatblock-issues#91]
Introduce a 'Static Rotation' option for paddles, allowing players to immobilize one or more paddles on the screen. When enabled, this feature will prevent the player from moving the selected paddle(s)

**Comment by OblivionCreator** [comment]
You'd be most likely better off using a deco for this usecase.

I'd be too concerned about a static paddle confusing players - and it'd not do much but artificially inflate their score at the end of the level.
