### ISSUE TITLE
[BUG] Ctrl+P no longer does anything

### ISSUE THREAD

**Issue by 9thCore** [DPS2004/Beatblock-issues#93]
**Describe the bug**
A keybind which previously worked and is mentioned in the editor guide, Ctrl+P, does not do anything upon use in the editor. P by itself still works fine, as far as I can tell.

**To Reproduce**
1. Open the editor
2. Press P
3. Level starts playing
4. Exit into editor, press Ctrl+P
5. Nothing..!

**Expected behavior**
Do the very thing the editor guide mentions and what it did the build before: play from the beginning of the level.

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by ItsKirby69** [comment]
You now need to press CTRL + SHIFT + P to play from the beginning of the level

**Comment by OblivionCreator** [comment]
This is fixed in the latest build of the game.
