### ISSUE TITLE
[BUG] Mine Hold that doesn't exsist.

### ISSUE THREAD

**Issue by GitHLurker** [DPS2004/Beatblock-issues#94]
Within less than 12 hours of posting a wip of my chart, an update came out and now it's broken and I don't know why.
[crashlog-1724113890.txt](https://github.com/user-attachments/files/16667210/crashlog-1724113890.txt)

**Additional context**
I tried deleting the whole map and replacing it so the chart file would be up to date (it wasn't initially somehow) but nothing changed.
[Time Traveler wip.zip](https://github.com/user-attachments/files/16667232/Time.Traveler.wip.zip)

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by DPS2004** [comment]
Fixed in dev
