### ISSUE TITLE
[BUG] game speed issue

### ISSUE THREAD

**Issue by B1rb3** [DPS2004/Beatblock-issues#97]
**The game speed resets after retrying the map**
This is an issue where if you retry a map at the end screen, this is not a problem when retrying on the pause screen or having the option “restart on: miss/barely or miss. Any other setting in the options of a song is not affected by this. Now I don’t know if this is a bug or intended, but it is a tidy job having to readjust the speed every session

**To Reproduce**
1. Go to any map and set the game speed to your liking 
(click on “play demo levels/custom levels”> click on any song> click on “options”> adjust the “game speed” option
2. Play the game until at the end screen
3. Click on “retry”
4. Notice the error

**Expected behavior**
? (Sorry “^^)

**Screenshots**
[https://youtu.be/p0yleTzEKWQ?si=lyTpqyeWecMPOhk7]

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

can confirm

**Comment by OblivionCreator** [comment]
Fixed in dev. Thanks for the report!
