### ISSUE TITLE
[BUG] Game speed change don't apply

### ISSUE THREAD

**Issue by CherryRage** [DPS2004/Beatblock-issues#99]
**Describe the bug**
Game speed don't apply to level This future (we didn't expect) - Camellia (only on this level, I didn't see problem with other level i dowloaded).  Level have same speed on different game speed value. Reseting game didn't fix anything.

**To Reproduce**
1. Play on different game speed This future (we didn't expect)

**Expected behavior**
Speed change when applied in game

**Screenshots**
https://www.youtube.com/watch?v=slK15rt28rg

**Additional context**
Beatblock is the best

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
I'm surprised we never ran into this bug more often! Fixed for next release.
